name: Build and Push Docker Image Tester 
## the github action will only run if the commit message
# is 'build test' and on branch 'tester'

on:
  push:
    branches: ["tester"]  # only run on push to tester
  workflow_dispatch:       # allows manual trigger

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, 'build test')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chamso2004/hawiyat-test:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
